config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end
  resources :recipe_foods, only: [ :destroy, :new, :create, :edit, :update ]
  resources :foods, only: [ :index, :new, :create, :destroy ]
  resources :recipes, only: [ :index, :show, :create, :destroy, :new, :update ]

  get '/public_recipes', to: 'recipes#public_recipes'
  get '/general_shopping_list', to: 'foods#general_shopping_list'

  # Defines the root path route ("/")
  root "foods#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  before_destroy :delete_associated_recipe_foods

  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, numericality: { greater_than_or_equal_to: 0 }
  validates :description, presence: true, length: { maximum: 200 }
  validates :public, inclusion: { in: [true, false] }

  def delete_associated_recipe_foods
    recipe_foods.destroy_all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe_food = RecipeFood.where(recipe_id: params[:id])
    # p @recipe_food
    @recipe = Recipe.find(params[:id])
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @recipe.user = current_user
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def public_recipes
    @public_recipes = Recipe.includes(:user, :recipe_foods).where(public: true)
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    toggle_public
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)

    redirect_to recipe_url(@recipe), notice: 'Public status was successfully updated.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def calculate_total_price(recipe_foods)
    total_price = 0

    recipe_foods.includes([:food]).each do |recipe_food|
      food = recipe_food.food
      food_price = food.price
      subtotal_price = food_price * recipe_food.quantity
      total_price += subtotal_price
    end

    total_price
  end
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div class="field remember-me">
    <%= form.check_box :public, class: "input-checkbox" %>
    <%= form.label :public, class: "label-checkbox" %>
  </div>

  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_public_recipe.html.erb
<div class="recipe-container flex-row">
  <div class="flex-column public-recipe-title">
    <h2><%= recipe.name %></h2>
    <h4>By: <%= recipe.user.name %></h4>
  </div>
  <div class="flex-column public-recipe-info">
    <p>Total food items: <strong><%= recipe.recipe_foods.size %></strong></p>
    <p>Total price: <strong>$<%= calculate_total_price(recipe.recipe_foods) %></strong></p>
    <%= link_to "See Recipe >", recipe, class: "add-food-btn"%>
  </div>
</div>

app/views/recipes/_public_toggle.html.erb
<%= form_for recipe, url: recipe_path(recipe), method: :patch do |f| %>
  <%= f.hidden_field :public, value: !recipe.public %>
  <%= f.submit recipe.public ? 'Make Private' : 'Make Public', class: 'form-public', id:'togle-button' %>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="recipe-show-container">
  <h1 class="align-center">
    <%= recipe.name %>
  </h2>

  <div class="flex-row recipe-section-1">
    <p class="flex-1">
      <strong>Preparation time:</strong>
      <%= recipe.preparation_time %>
    </p>
    <% if can? :edit, recipe %>
        <%= render partial: 'recipes/public_toggle', locals: { recipe: recipe } %>
    <% end %>
  </div>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

</div>

app/views/recipes/_recipeCard.html.erb
<div class="recipes-name-n-btn">

  <div>
  <h2>
    <%= recipe.name %>
  </h2>

  <%= button_to "REMOVE", recipe, method: :delete, class: "remove-recipe" %>

  </div>

  <p>
    <%= recipe.description %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="title">Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <a href="<%= recipe_path(recipe) %>">
      <%= render partial: 'recipeCard', locals: { recipe: recipe } %>
    </a>
  <% end %>
</div>

<%= link_to "New recipe", new_recipe_path, class: "add-food-btn align-center" %>

app/views/recipes/new.html.erb
<h1 class="form-title">New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div class="align-center">
  <%= link_to "Back to recipes", recipes_path, class: "form-link" %>
</div>

app/views/recipes/public_recipes.html.erb
<h1 class="title">Public Recipes</h1>
<% @public_recipes.each do |public_recipe| %>
  <%= render partial: 'public_recipe', locals: {recipe: public_recipe} %>
<% end %>

app/views/recipes/show.html.erb
<p class="notice"><%= notice %></p>

<%= render @recipe %>
<hr>
<div class="recipe-section-2">
  
  <div class="recipe-actions">
    <%= link_to 'Generate shopping list', general_shopping_list_path, class: "add-food-btn recipe-action" %>

    <%= link_to 'Add ingredient', new_recipe_food_path(recipe_id: @recipe.id), class: "add-food-btn recipe-action" if can? :edit, @recipe %>
  </div>


  <table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe_food.includes([:food]).each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
        <td>$ <%= recipe_food.quantity * recipe_food.food.price %></td>
        <td class="recipe-food-actions">
          <%= link_to 'Modify', edit_recipe_food_path(recipe_food), class: "modify-button" if can? :edit, recipe_food %> 
          <%= button_to 'Remove', recipe_food_path(recipe_food), class: "btn-delete", method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, recipe_food %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>



  <%= link_to "Back to recipes", recipes_path, class: "add-food-btn recipe-action" %>

  <%= button_to "Destroy this recipe", @recipe, class: "btn-delete", method: :delete if can? :destroy, @recipe %>
</div>