config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end
  resources :recipe_foods, only: [ :destroy, :new, :create, :edit, :update ]
  resources :foods, only: [ :index, :new, :create, :destroy ]
  resources :recipes, only: [ :index, :show, :create, :destroy, :new, :update ]

  get '/public_recipes', to: 'recipes#public_recipes'
  get '/general_shopping_list', to: 'foods#general_shopping_list'

  # Defines the root path route ("/")
  root "foods#index"
end

app/models/food.rb
class Food < ApplicationRecord
  before_destroy :delete_associated_recipe_foods

  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def delete_associated_recipe_foods
    recipe_foods.destroy_all
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @foods = current_user.foods
  end

  def new
    @food = Food.new
    @food.user = current_user
  end

  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_url, notice: 'Food was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
    end
  end

  def general_shopping_list
    @recipes = Recipe.where(user: current_user)
    @recipe_foods = RecipeFood.where(recipe: @recipes)
    @foods = Food.where(user: current_user)

    @needs = helpers.calculate_total_items(@recipe_foods)
    @array = helpers.calculate_food_totals(@foods)
    @inventory = @array[0]
    @prices = @array[1]

    @shop = helpers.calculate_totals_needed(@inventory, @needs)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
  def calculate_total_items(recipe_foods)
    result = {}

    recipe_foods.includes([:food]).each do |recipe_food|
      element = recipe_food.food.name
      quantity = recipe_food.quantity

      if result.key?(element)
        result[element] += quantity
      else
        result[element] = quantity
      end
    end
    result
  end

  def calculate_food_totals(foods)
    result_quantity = {}
    unit_price = {}

    foods.each do |food|
      element = food.name
      quantity = food.quantity
      price = food.price

      if result_quantity.key?(element)
        old_price = unit_price[element]
        old_quantity = result_quantity[element]

        new_price = ((old_price * old_quantity) + (price * quantity)) / (quantity + old_quantity)

        result_quantity[element] += quantity
        unit_price[element] = new_price.round(2)
      else
        result_quantity[element] = quantity
        unit_price[element] = price
      end
    end
    [result_quantity, unit_price]
  end

  def calculate_totals_needed(inventory, needs)
    shop = {}
    needs.each do |element, quantity|
      inventory_quantity = inventory[element] || 0
      need_quantity = quantity - inventory_quantity
      shop[element] = need_quantity if need_quantity.positive?
    end
    shop
  end

  def calculate_price(shop, price)
    total = 0
    shop.each do |element, quantity|
      total += price[element] * quantity
    end
    total
  end
end

app/views/foods/_food.html.erb
<tr>
  <td><%= food.name %></td>
  <td><%= food.quantity %></td>
  <td><%= food.measurement_unit %></td>
  <td>$<%= food.price %></td>
  <td>
    <%= button_to 'Delete', food_path(food), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-delete' %>
  </td>
</tr>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
   <%= form.select :measurement_unit, ['Units', 'Kilogram (kg)', 'Gram (g)', 'Liter (l)', 'Milliliter (ml)' ] %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.text_field :quantity %>
  </div>

  <%= form.hidden_field :user_id, value: food.user.id %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/general_shopping_list.html.erb
<h1 class="title">General Shopping List</h1>

<div class="shopping-container">
  <div class="flex-row">
    <p>Amount of food items to buy: <%= @shop.length %></p>
    <p>Total value of food needed: <%= calculate_price(@shop, @prices) %></p>
  </div>

  <table>
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @shop.each do |element, quantity| %>
        <tr>
          <td><%= element %></td>
          <td><%= quantity %> <%= @foods.find_by(name: element).measurement_unit %></td>
          <td>$ <%= @prices[element] * quantity %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="food-header flex-row"> 
  <h1 class="section-title">Foods</h1>
  <%= link_to "New food", new_food_path, class: "add-food-btn" %>
</div>

<table class="table-container">
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Measurement Unit</th>
      <th>Unit Price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <%= render food %>
    <% end %>
  </tbody>
</table>

app/views/foods/new.html.erb
<h1 class="form-title">New food</h1>

<%= render "form", food: @food %>

<br>

<div class="align-center">
  <%= link_to "Back to foods", foods_path, class: "form-link" %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>