config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end
  resources :recipe_foods, only: [ :destroy, :new, :create, :edit, :update ]
  resources :foods, only: [ :index, :new, :create, :destroy ]
  resources :recipes, only: [ :index, :show, :create, :destroy, :new, :update ]

  get '/public_recipes', to: 'recipes#public_recipes'
  get '/general_shopping_list', to: 'foods#general_shopping_list'

  # Defines the root path route ("/")
  root "foods#index"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /recipe_foods/new
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new
    @available_foods = Food.where(user: current_user)
  end

  # POST /recipe_foods or /recipe_foods.json
  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe = @recipe_food.recipe

    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipe_path(@recipe), notice: 'Recipe food was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe = @recipe_food.recipe
    @recipe_food.destroy

    respond_to do |format|
      format.html { redirect_to recipe_path(@recipe), notice: 'Recipe food was successfully deleted.' }
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    p params
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(update_recipe_food_params)
      redirect_to recipe_path(@recipe_food.recipe_id), notice: 'The recipe food was successfully updated.'
    else
      flash[:alert] = 'Failed to update recipe food'
      redirect_back_or_to root_path
    end
  end

  private

  def update_recipe_food_params
    params.require(:recipe_food).permit(:quantity)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :recipe_id, :food_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
<%= form_with(model: recipe_food) do |form| %>
  <% if recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :food_id, style: "display: block" %>
    <%= form.collection_select(:food_id, available_foods, :id, :name, {}, {}) %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.text_field :quantity %>
  </div>

  <%= form.hidden_field :recipe_id, value: recipe.id %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
  <p>
    <strong>Quantity:</strong>
    <%= recipe_food.quantity %>
  </p>

  <p>
    <strong>Recipe:</strong>
    <%= recipe_food.recipe_id %>
  </p>

  <p>
    <strong>Food:</strong>
    <%= recipe_food.food_id %>
  </p>

</div>

app/views/recipe_foods/edit.html.erb
<h1 class="title">Edit recipe food</h1>

<div>
    <%= form_with model: @recipe_food, url: recipe_food_path(@recipe_food), class: "form-container", method: :patch do |f| %>
        <h2 class="">Editing: <%= @recipe_food.food.name %></h2>
        <div class="flex-column align-start">
            <%= f.label :quantity %>
            <%= f.number_field :quantity, placeholder: 'New Quantity', class: "input-controll", min: 0 %>
        </div>
        <div>
            <%= f.submit 'Edit', class: "send-button" %>
        </div>
    <% end %>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<h1 class="form-title">New recipe food</h1>

<%= render "form", recipe_food: @recipe_food, recipe: @recipe, available_foods: @available_foods %>

<br>

<div class="align-center">
  <%= link_to "Back to recipe", recipe_path(@recipe), class: "form-link" %>
</div>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>

  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>